FROM node:alpine
COPY . /app
WORKDIR /app
CMD node app.js

# To build image:
# docker build -t hello-docker .

# To list the image from docker:
# docker images or docker image ls

# To run the image:
# docker run <name-of-image>

# To push the image to docker-hub:
# e.g. docker tag hello-docker:latest bfactor/hello-docker
# docker images (look for <bfactor/hello-docker> images)
# docker push bfactor/hello-docker

